In [ ]:
import numpy as np

# 1. Create a 1D array from a Python list
arr = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr)

# 2. Perform a fast element-wise operation (multiply every item by 2)
doubled_arr = arr * 2
print("Doubled Array: ", doubled_arr)

# 3. Calculate the sum of all elements
total_sum = np.sum(arr)
print("Sum of elements:", total_sum)


Original Array: [1 2 3 4 5]
Doubled Array:  [ 2  4  6  8 10]
Sum of elements: 15


In [ ]:
import sys
print(sys.version)


3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]


In [ ]:
import numpy as np
arr=np.array([1,3,5,8,10])
arr
print(arr)

[ 1  3  5  8 10]


In [ ]:
import numpy as np
arr=[[1,2,3],[4,5,6],[7,8,9]]
np.array(arr)



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
ar=np.arange(1,100,9)
ar

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [ ]:
arr=np.linspace(1,100,50)
print(arr)

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]


## we are doing random generation function

In [ ]:
np.random.rand(6)

array([0.22967856, 0.61947671, 0.69632796, 0.46209112, 0.87089611,
       0.33647868])

In [ ]:
np.random.randn(10)

array([-1.25364125, -1.30038551,  0.64210911,  0.40953454,  1.18812446,
       -0.37646069,  0.34439341,  1.91740729,  0.78096132, -1.34989579])

In [ ]:
np.random.randint(10,20,10)

array([18, 11, 11, 15, 13, 13, 19, 11, 12, 14], dtype=int32)

##Array attribute

In [10]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr.size


9

In [14]:
arr.shape

(3, 3)

In [17]:
arr.dtype

dtype('int64')

##Array methods

In [21]:
print(arr.max())

9


In [23]:
print(arr.min())

1


In [25]:
print(arr.sum())

45


In [27]:
print(np.sum(arr,axis=1))
print(np.sum(arr,axis=0))

[ 6 15 24]
[12 15 18]


In [29]:
print(arr.mean())

5.0


In [31]:
print(arr.std())

2.581988897471611


In [33]:
print(arr.var())

6.666666666666667


In [34]:
arr=np.arange(1,34)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [39]:
arr.reshape(11,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])